spring:
  application:
    name: demo
    dattasource:
      url:jdbc:postgressql://localhost:5432/testdb
      usernama:test
      password:test
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true